server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    # Rutas del router de Angular: si el fichero no existe, sirve index.html
    location / {
        try_files $uri $uri/ /index.html;
    }
}
