--Tiene que coincidir con la entidad Usuario.java
CREATE TABLE IF NOT EXISTS usuarios (
    id_usuario BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    --email y contrasena solo los tienen los superusuarios (cuentas de inicio de sesión).
    --La contraseña se guarda cifrada con BCrypt (hash de 60 caracteres), nunca en texto plano.
    email      VARCHAR(50) UNIQUE,
    contrasena VARCHAR(72),
    nombre     VARCHAR(50) NOT NULL,
    apellido1  VARCHAR(30) NOT NULL,
    apellido2  VARCHAR(30),
    prefijo    VARCHAR(6) NOT NULL,
    telefono1  VARCHAR(9) NOT NULL,
    telefono2  VARCHAR(9),
    dni        VARCHAR(9) NOT NULL UNIQUE,
    sexo       VARCHAR(1) NOT NULL CHECK (sexo IN ('M', 'F')),
    verificado BOOLEAN NOT NULL DEFAULT FALSE,
    codigo_verificacion VARCHAR(5),
    id_usuario_principal BIGINT REFERENCES usuarios(id_usuario) ON DELETE CASCADE
);

--El usuario con el que inicie sesión tiene los datos completos, los subusuarios solo nombre, apellidos y sexo