CREATE TABLE IF NOT EXISTS usuarios ( --usuarios
    id_usuario BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email      VARCHAR(50) UNIQUE,
    contrasena VARCHAR(72),
    nombre     VARCHAR(50) NOT NULL,
    apellido1  VARCHAR(30) NOT NULL,
    apellido2  VARCHAR(30),
    prefijo    VARCHAR(6),
    telefono1  VARCHAR(9),
    telefono2  VARCHAR(9),
    dni        VARCHAR(9) UNIQUE,
    sexo       VARCHAR(1) NOT NULL CHECK (sexo IN ('M', 'F')),
    verificado BOOLEAN NOT NULL DEFAULT FALSE,
    codigo_verificacion VARCHAR(5),
    id_usuario_principal BIGINT REFERENCES usuarios(id_usuario) ON DELETE CASCADE,
    saldo NUMERIC(12, 2) NOT NULL DEFAULT 0.00
);

CREATE TABLE IF NOT EXISTS movimientos (--tipos de movimientos de dinero
    id_movimiento BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo  VARCHAR(40) NOT NULL UNIQUE,
    gasto VARCHAR(1) NOT NULL CHECK (gasto IN ('S', 'N'))
);

INSERT INTO movimientos (tipo, gasto) VALUES
    ('Fijos', 'S'),
    ('Variables', 'S'),
    ('Gastos de ocio', 'S'),
    ('Comida y casa', 'S'),
    ('Hijos', 'S'),
    ('Transporte/vehículo', 'S'),
    ('Inversiones', 'S'),
    ('Imprevistos', 'S'),
    ('Otros gastos', 'S'),
    ('Nómina', 'N'),
    ('Beneficios de inversiones', 'N'),
    ('Regalos', 'N'),
    ('Otros', 'N')
ON CONFLICT (tipo) DO NOTHING;

CREATE TABLE IF NOT EXISTS movimientos_usuarios ( --tabla que indica los movimientos de cada usuario
    id_movimiento_usuario BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario    BIGINT NOT NULL REFERENCES usuarios(id_usuario) ON DELETE CASCADE,
    id_movimiento BIGINT NOT NULL REFERENCES movimientos(id_movimiento) ON DELETE CASCADE,
    descripcion   VARCHAR(100) NOT NULL,
    fecha_movimiento     DATE,
    fecha_fin_movimiento DATE
);